### ISSUE TITLE
terminate called after throwing an instance of 'boost::wrapexcept<boost::system::system_error>'   what():  resolve: Service not found

### ISSUE THREAD

**Issue by Robotic-HFUT-JACK** [arsh09/franka_telemanipulation#3]
Hi，Arshad，
1. Are the two robots connected to the same computer? If not, how do the two robots communicate with each other?  Did you use router or WiFi？
2. How should  I run the './leader_franka <server-port> <follower-pc-hostname> <leader-robot-host>',the <server-port> is the name of my wired connection with leader robot，<leader-robot-host> is the ip of leader robot，and what is the <follower-pc-hostname> mean，the ip of follower computer?

**Comment by arsh09** [comment]
1) You can connect the next 2 robots to the same computer but that would require changing 172.16.0.2 to some other domain for one robot. Then the ‘other PC IP’ will be ‘local host’

I tested the library by connecting an Ethernet cable between 2 computers and adding a network (in Ubuntu network manager). Note that this is only possible if you have 2 Ethernet card on each computer as the first card will be used for Ethernet for robot.

You can also use the WiFi where both computer are connected to same WiFi i.e. they are on same local network for example 192.168.100.XXX where XXX is different for each computer and 192.168.100 is your router NAT network domain (it may be different for your router , use ifconfig command to find the IP address). 


2. The ‘other-pc-ip’ is basically leader PC IP on follower side and vice versa.

**Comment by Robotic-HFUT-JACK** [comment]
Hi,Arshad
Sorry to bother you again.
I just connect 1 robot with my computer and without any other connection, and run <./follower_franka franka_robot 192.168.1.110> (franka_robot is the wire port name,192.168.1.110 is the robot ip), it works. But when I run <./leader_franka franka_robot 192.168.1.130 192.168.1.110>, output error "terminate called after throwing an instance of 'boost::wrapexcept <boost::system::system_error>'  what():  resolve: Service not found", (where 192.168.1.130 is the ip of my computer). So, the 192.168.1.130 should instead by the follower PC IP？
Here is the network setting of my computer:
![Screenshot from 2023-01-11 17-23-41](https://user-images.githubusercontent.com/49557678/211768656-7d140970-057b-4385-aec9-d1811bdbf244.png)
Another question is the code in follower_franka.cpp and leader_franka.cpp:
In follower_franka.cpp :
```
 int main(int argc, char** argv) 
{
    if (argc != 3)
    {
        std::cerr << "Usage: "  << argv[0] << "  <server-port>  <follower-robot-hostname> \n";
        return 1;
    }
```
where you just defined the "server-port" and f"ollower robot ip" when run ./follower_franka, but in leader_franka.cpp:
```
int main(int argc, char** argv) 
{
    if (argc != 4)
    {
        std::cerr << "Usage: "  << argv[0] << "  <server-port>  <server-pc-host> <leader-robot-hostname> \n";
        return 1;
    }
```
you defined three input. So, I'm wondering how can the follower robot get the leader robot's motion when two robots are connect with two computers, which .cpp file make it happen.
Thank you very much,
Best regards

**Comment by arsh09** [comment]
Hi, 

1) Please note that for true teleoperation, you should have the two computers connected with each robot. The two computers can connect to each other over either a WiFi network or a wired network. The wired network can be a single Ethernet cable between the two computers or via a router. Also note that if you use 'wired' connection between two computers, you will need TWO ethernet card on each computer. The first card will be used to connect a Franka and the second one will be used to connect the other-computer. 

2) You are getting this **resolve error** because (I am guessing here) you have only 1 ethernet card in your computer and you are connecting the Panda as well as the wired connection to it. You can easily see this if you open a terminal and type `ifconfig` and see what networks are available. 

3) As I mentioned in the readme, the communication between the two computers is UDP-based where the follower side is a UDP-server and the leader side is always a UDF-client. So you NEED to tell the UDP-client what is the port and IP of the UDP-server that is why there are 4 arguments on the leader side where as the UPD-server side needs to know on what port the UDP-server should start that is why on follower side (UPD-server) there are only 3 arguments. 

4) To run the demo, make sure that both robots (leader and follower) are connected to their respective computers. Then make sure that both respective computers are connected to the same network. Lets assume that both computers are connected to the same WiFi network. This means that you can find out the WiFi IP assigned to each network using ifconfig and then use it to ping the other computer such as: 

- Assuming that Leader Computer has WiFi IP 192.168.1.10 and Follower Computer has WiFi IP 192.168.1.20. So from the Follower computer, you can do: 
```bash
ping 192.168.1.10 
```

and from the Leader computer: 

```bash
ping 192.168.1.20
```

If these pings work, then you can run the ./follower_franka (on Follower Computer) as: 

```bash
$ ./follower_franka 45454 <Follower-Franka-Robot-IP>
```

and then run the following on Leader computer: 

```bash
$ ./leader_franka 45454 192.168.1.20 <Leader-Franka-Robot-IP>
```

Best, 

Arsh

**Comment by Robotic-HFUT-JACK** [comment]
Hi，Arshad
Thank you very much for your detailed explanation, it is very useful for me.
Best ragards
